"""Add PluginCategory table and extend PluginMeta

Revision ID: 0d227417b23b
Revises: a39cc69515de
Create Date: 2026-01-23 10:32:28.745419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d227417b23b'
down_revision = 'a39cc69515de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_plugin_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_de', sa.String(length=50), nullable=False),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_plugin_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_plugin_category_code'), ['code'], unique=True)

    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=False, server_default='ti ti-puzzle'))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_marketplace_plugin_meta_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_plugin_category', 'marketplace_plugin_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plugin_category', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_meta_category_id'))
        batch_op.drop_column('category_id')
        batch_op.drop_column('icon')

    with op.batch_alter_table('marketplace_plugin_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_category_code'))

    op.drop_table('marketplace_plugin_category')
    # ### end Alembic commands ###
