"""Add allow_one_time_purchase to PluginMeta

Revision ID: 516421db44a2
Revises: fa26e523fd75
Create Date: 2026-01-18 10:42:44.781172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516421db44a2'
down_revision = 'fa26e523fd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_one_time_purchase', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.drop_column('allow_one_time_purchase')

    # ### end Alembic commands ###
