"""Initial marketplace models

Revision ID: ce95b04ec33c
Revises: 
Create Date: 2026-01-16 18:10:15.135773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce95b04ec33c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betreiber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('impressum', sa.Text(), nullable=True),
    sa.Column('datenschutz', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('land', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('rechtsform', sa.String(length=50), nullable=True),
    sa.Column('geschaeftsfuehrer', sa.String(length=500), nullable=True),
    sa.Column('handelsregister_gericht', sa.String(length=100), nullable=True),
    sa.Column('handelsregister_nummer', sa.String(length=50), nullable=True),
    sa.Column('ust_idnr', sa.String(length=20), nullable=True),
    sa.Column('wirtschafts_idnr', sa.String(length=20), nullable=True),
    sa.Column('inhaltlich_verantwortlich', sa.String(length=200), nullable=True),
    sa.Column('impressum_optionen', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('beschreibung', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_key'), ['key'], unique=True)

    op.create_table('marketplace_plugin_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_plugin_meta_name'), ['name'], unique=True)

    op.create_table('marketplace_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_project_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_marketplace_project_slug'), ['slug'], unique=True)

    op.create_table('modul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=100), nullable=True),
    sa.Column('min_permission', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modul_code'), ['code'], unique=True)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.String(length=200), nullable=True),
    sa.Column('modul', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permission_modul'), ['modul'], unique=False)

    op.create_table('rolle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('beschreibung', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rolle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rolle_name'), ['name'], unique=True)

    op.create_table('v_flask_system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('v_flask_system_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_v_flask_system_status_key'), ['key'], unique=True)

    op.create_table('lookup_wert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategorie', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('farbe', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('betreiber_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['betreiber_id'], ['betreiber.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kategorie', 'code', 'betreiber_id', name='uq_lookup_kategorie_code_betreiber')
    )
    with op.batch_alter_table('lookup_wert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_wert_betreiber_id'), ['betreiber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookup_wert_kategorie'), ['kategorie'], unique=False)

    op.create_table('marketplace_license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['marketplace_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'plugin_name', name='uq_project_plugin')
    )
    with op.batch_alter_table('marketplace_license', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_license_plugin_name'), ['plugin_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_license_project_id'), ['project_id'], unique=False)

    op.create_table('marketplace_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['marketplace_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    with op.batch_alter_table('marketplace_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_order_project_id'), ['project_id'], unique=False)

    op.create_table('rolle_permission',
    sa.Column('rolle_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['rolle_id'], ['rolle.id'], ),
    sa.PrimaryKeyConstraint('rolle_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('vorname', sa.String(length=50), nullable=False),
    sa.Column('nachname', sa.String(length=50), nullable=False),
    sa.Column('rolle_id', sa.Integer(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_typ', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['rolle_id'], ['rolle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('modul', sa.String(length=50), nullable=True),
    sa.Column('aktion', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('wichtigkeit', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_modul'), ['modul'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_wichtigkeit'), ['wichtigkeit'], unique=False)

    op.create_table('help_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schluessel', sa.String(length=100), nullable=False),
    sa.Column('titel', sa.String(length=200), nullable=False),
    sa.Column('inhalt_markdown', sa.Text(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('plugin', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('help_text', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_text_schluessel'), ['schluessel'], unique=True)

    op.create_table('v_flask_plugin_activation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by_id', sa.Integer(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('v_flask_plugin_activation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_v_flask_plugin_activation_plugin_name'), ['plugin_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v_flask_plugin_activation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v_flask_plugin_activation_plugin_name'))

    op.drop_table('v_flask_plugin_activation')
    with op.batch_alter_table('help_text', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_text_schluessel'))

    op.drop_table('help_text')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_wichtigkeit'))
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_modul'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('rolle_permission')
    with op.batch_alter_table('marketplace_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_order_project_id'))

    op.drop_table('marketplace_order')
    with op.batch_alter_table('marketplace_license', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_license_project_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_license_plugin_name'))

    op.drop_table('marketplace_license')
    with op.batch_alter_table('lookup_wert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_wert_kategorie'))
        batch_op.drop_index(batch_op.f('ix_lookup_wert_betreiber_id'))

    op.drop_table('lookup_wert')
    with op.batch_alter_table('v_flask_system_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_v_flask_system_status_key'))

    op.drop_table('v_flask_system_status')
    with op.batch_alter_table('rolle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rolle_name'))

    op.drop_table('rolle')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_modul'))
        batch_op.drop_index(batch_op.f('ix_permission_code'))

    op.drop_table('permission')
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modul_code'))

    op.drop_table('modul')
    with op.batch_alter_table('marketplace_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_project_slug'))
        batch_op.drop_index(batch_op.f('ix_marketplace_project_api_key'))

    op.drop_table('marketplace_project')
    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_meta_name'))

    op.drop_table('marketplace_plugin_meta')
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_key'))

    op.drop_table('config')
    op.drop_table('betreiber')
    # ### end Alembic commands ###
