"""Add ProjectType, PluginPrice, PluginVersion, LicenseHistory and extend existing models

Revision ID: fa26e523fd75
Revises: ce95b04ec33c
Create Date: 2026-01-17 20:54:21.936919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa26e523fd75'
down_revision = 'ce95b04ec33c'
branch_labels = None
depends_on = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create marketplace_project_type if not exists
    if not table_exists('marketplace_project_type'):
        op.create_table('marketplace_project_type',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('code', sa.String(length=50), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('trial_days', sa.Integer(), nullable=False),
            sa.Column('is_free', sa.Boolean(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('sort_order', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('marketplace_project_type', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_marketplace_project_type_code'), ['code'], unique=True)

    # Create marketplace_plugin_price if not exists
    if not table_exists('marketplace_plugin_price'):
        op.create_table('marketplace_plugin_price',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('plugin_id', sa.Integer(), nullable=False),
            sa.Column('project_type_id', sa.Integer(), nullable=False),
            sa.Column('price_cents', sa.Integer(), nullable=False),
            sa.Column('billing_cycle', sa.String(length=20), nullable=False),
            sa.Column('currency', sa.String(length=3), nullable=False),
            sa.Column('usage_unit', sa.String(length=50), nullable=True),
            sa.Column('usage_price_per_unit', sa.Integer(), nullable=True),
            sa.Column('included_units', sa.Integer(), nullable=True),
            sa.Column('setup_fee_cents', sa.Integer(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('valid_from', sa.DateTime(), nullable=False),
            sa.Column('valid_until', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['plugin_id'], ['marketplace_plugin_meta.id'], ),
            sa.ForeignKeyConstraint(['project_type_id'], ['marketplace_project_type.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('plugin_id', 'project_type_id', 'billing_cycle', name='uq_plugin_projecttype_billing')
        )
        with op.batch_alter_table('marketplace_plugin_price', schema=None) as batch_op:
            batch_op.create_index('idx_price_active', ['is_active'], unique=False)
            batch_op.create_index(batch_op.f('ix_marketplace_plugin_price_plugin_id'), ['plugin_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_marketplace_plugin_price_project_type_id'), ['project_type_id'], unique=False)

    # Create marketplace_plugin_version if not exists
    if not table_exists('marketplace_plugin_version'):
        op.create_table('marketplace_plugin_version',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('plugin_id', sa.Integer(), nullable=False),
            sa.Column('version', sa.String(length=20), nullable=False),
            sa.Column('changelog', sa.Text(), nullable=True),
            sa.Column('release_notes', sa.Text(), nullable=True),
            sa.Column('min_v_flask_version', sa.String(length=20), nullable=True),
            sa.Column('is_breaking_change', sa.Boolean(), nullable=False),
            sa.Column('is_stable', sa.Boolean(), nullable=False),
            sa.Column('is_current', sa.Boolean(), nullable=False),
            sa.Column('download_count', sa.Integer(), nullable=False),
            sa.Column('released_at', sa.DateTime(), nullable=False),
            sa.Column('released_by', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['plugin_id'], ['marketplace_plugin_meta.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('plugin_id', 'version', name='uq_plugin_version')
        )
        with op.batch_alter_table('marketplace_plugin_version', schema=None) as batch_op:
            batch_op.create_index('idx_version_current', ['plugin_id', 'is_current'], unique=False)
            batch_op.create_index(batch_op.f('ix_marketplace_plugin_version_plugin_id'), ['plugin_id'], unique=False)

    # Create plugin_config if not exists
    if not table_exists('plugin_config'):
        op.create_table('plugin_config',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('plugin_name', sa.String(length=100), nullable=False),
            sa.Column('key', sa.String(length=100), nullable=False),
            sa.Column('value', sa.Text(), nullable=True),
            sa.Column('value_type', sa.String(length=20), nullable=False),
            sa.Column('is_secret', sa.Boolean(), nullable=False),
            sa.Column('description', sa.String(length=200), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('updated_by_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('plugin_name', 'key', name='uq_plugin_config_plugin_key')
        )
        with op.batch_alter_table('plugin_config', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_plugin_config_plugin_name'), ['plugin_name'], unique=False)

    # Create marketplace_license_history if not exists
    if not table_exists('marketplace_license_history'):
        op.create_table('marketplace_license_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('license_id', sa.Integer(), nullable=False),
            sa.Column('action', sa.String(length=30), nullable=False),
            sa.Column('old_status', sa.String(length=20), nullable=True),
            sa.Column('new_status', sa.String(length=20), nullable=True),
            sa.Column('old_expires_at', sa.DateTime(), nullable=True),
            sa.Column('new_expires_at', sa.DateTime(), nullable=True),
            sa.Column('old_billing_cycle', sa.String(length=20), nullable=True),
            sa.Column('new_billing_cycle', sa.String(length=20), nullable=True),
            sa.Column('performed_by', sa.String(length=255), nullable=True),
            sa.Column('performed_by_type', sa.String(length=20), nullable=False),
            sa.Column('reason', sa.Text(), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('metadata_json', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['license_id'], ['marketplace_license.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('marketplace_license_history', schema=None) as batch_op:
            batch_op.create_index('idx_history_action', ['action'], unique=False)
            batch_op.create_index(batch_op.f('ix_marketplace_license_history_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_marketplace_license_history_license_id'), ['license_id'], unique=False)

    # Extend marketplace_license with new columns (only if not already present)
    if not column_exists('marketplace_license', 'status'):
        with op.batch_alter_table('marketplace_license', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
            batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=False, server_default='once'))
            batch_op.add_column(sa.Column('next_billing_date', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('plugin_price_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_marketplace_license_plugin_price_id'), ['plugin_price_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_marketplace_license_status'), ['status'], unique=False)
            batch_op.create_foreign_key('fk_license_plugin_price', 'marketplace_plugin_price', ['plugin_price_id'], ['id'])

    # Extend marketplace_plugin_meta with new columns (only if not already present)
    if not column_exists('marketplace_plugin_meta', 'category'):
        with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
            batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column('min_v_flask_version', sa.String(length=20), nullable=True))
            batch_op.add_column(sa.Column('has_trial', sa.Boolean(), nullable=False, server_default='1'))
            batch_op.create_index(batch_op.f('ix_marketplace_plugin_meta_category'), ['category'], unique=False)

    # Extend marketplace_project with new columns (only if not already present)
    if not column_exists('marketplace_project', 'project_type_id'):
        with op.batch_alter_table('marketplace_project', schema=None) as batch_op:
            batch_op.add_column(sa.Column('project_type_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))
            batch_op.create_index(batch_op.f('ix_marketplace_project_project_type_id'), ['project_type_id'], unique=False)
            batch_op.create_foreign_key('fk_project_project_type', 'marketplace_project_type', ['project_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_project', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_project_type', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_marketplace_project_project_type_id'))
        batch_op.drop_column('trial_end_date')
        batch_op.drop_column('trial_start_date')
        batch_op.drop_column('project_type_id')

    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_meta_category'))
        batch_op.drop_column('has_trial')
        batch_op.drop_column('min_v_flask_version')
        batch_op.drop_column('category')

    with op.batch_alter_table('marketplace_license', schema=None) as batch_op:
        batch_op.drop_constraint('fk_license_plugin_price', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_marketplace_license_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_license_plugin_price_id'))
        batch_op.drop_column('plugin_price_id')
        batch_op.drop_column('next_billing_date')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('status')

    with op.batch_alter_table('marketplace_license_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_license_history_license_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_license_history_created_at'))
        batch_op.drop_index('idx_history_action')

    op.drop_table('marketplace_license_history')
    with op.batch_alter_table('plugin_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_config_plugin_name'))

    op.drop_table('plugin_config')
    with op.batch_alter_table('marketplace_plugin_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_version_plugin_id'))
        batch_op.drop_index('idx_version_current')

    op.drop_table('marketplace_plugin_version')
    with op.batch_alter_table('marketplace_plugin_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_price_project_type_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_price_plugin_id'))
        batch_op.drop_index('idx_price_active')

    op.drop_table('marketplace_plugin_price')
    with op.batch_alter_table('marketplace_project_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_project_type_code'))

    op.drop_table('marketplace_project_type')
    # ### end Alembic commands ###
