"""Add phase field to PluginMeta

Revision ID: fb6e2ea801cc
Revises: 516421db44a2
Create Date: 2026-01-23 09:30:27.842500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6e2ea801cc'
down_revision = '516421db44a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('primary', sa.String(length=7), nullable=False),
    sa.Column('secondary', sa.String(length=7), nullable=False),
    sa.Column('accent', sa.String(length=7), nullable=False),
    sa.Column('neutral', sa.String(length=7), nullable=False),
    sa.Column('info', sa.String(length=7), nullable=False),
    sa.Column('success', sa.String(length=7), nullable=False),
    sa.Column('warning', sa.String(length=7), nullable=False),
    sa.Column('error', sa.String(length=7), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.String(length=20), nullable=False, server_default='alpha'))
        batch_op.create_index(batch_op.f('ix_marketplace_plugin_meta_phase'), ['phase'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('totp_backup_codes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('totp_enabled_at')
        batch_op.drop_column('totp_backup_codes')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('marketplace_plugin_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_plugin_meta_phase'))
        batch_op.drop_column('phase')

    op.drop_table('color_palette')
    # ### end Alembic commands ###
